config/routes.rb
Ultimatejoke::Application.routes.draw do

  resources :users

    root to: 'static_pages#home'

    resources :jokes
    resource :user_session
    
    put '/jokes/:id/:action' => 'jokes#upvote'
	put '/jokes/:id/:action' => 'jokes#downvote'

    post '/users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_to_admin
    post '/users/:id/demote_to_user' => 'users#demote_to_user', :as => :demote_to_user

    post '/login' => 'user_sessions#create'
    get '/login' => 'user_sessions#new'
    get '/logout' => 'user_sessions#destroy'
 
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
	has_many :jokes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => [:show, :edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    if current_user && current_user.id.to_s == params[:id].to_s || current_user_is_admin
      @user = User.find(params[:id])
    else
      flash[:warning] = "Cannot edit info of another user!"
      redirect_to jokes_path
    end
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if current_user && current_user.id.to_s == @user.id.to_s || current_user_is_admin
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:warning] = "Cannot edit info of another user!"
      redirect_to jokes_path
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user && current_user.id.to_s == params[:id].to_s || current_user_is_admin
      @user = User.find(params[:id])
      @user.destroy

      flash[:warning] = "User account deleted!"
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    else
      flash[:warning] = "Cannot delete the account of another user!"
      redirect_to users_url
    end
    
  end
  #Promote and demote admin statuses
  def promote_to_admin
    if current_user_is_admin
      @user = User.find(params[:id])
      @user.role = "admin"
      if @user.save
        flash[:success] = "Promoted #{@user.email} to admin!"
        redirect_to users_url
      else
        flash[:warning] = "Something went wrong when promoting #{@user.email} to admin!"
        redirect_to users_url
      end 
    else 
      flash[:warning] = "You cannot promote users since you're not an admin!"
      redirect_to users_url
    end 
  end
  def demote_to_user
    if current_user_is_admin
      @user = User.find(params[:id])
      @user.role = ""
      if @user.save
        flash[:success] = "Demoted #{@user.email} to user!"
        redirect_to users_url
      else
        flash[:warning] = "Something went wrong when promoting #{@user.email} to admin!"
        redirect_to users_url
      end
    else
      flash[:warning] = "You cannot demote users since you're not an admin!" 
      redirect_to users_url
    end 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </br>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :placeholder => "Email" %>
  </div>

  </br>

  <div class="field">
    <%= f.label(:password, "Password") %><br />
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>

  </br>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, :placeholder => "Password again" %>
  </div>

  </br>

  <div class="actions">
    <button class="btn btn-primary" type="submit">
    Submit
    </button>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Delete account', @user, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %>
<br/><br/>
<%= link_to 'Back', @user, :class => "btn btn-inverse" %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class='users-table'>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td>
      <% if user.role == "admin" %>
       <span class='user-is-admin'>Admin</span> 
      <% end %>
    </td>
    <td>
      <div class='btn-group'>
        <% if user.role == "admin" %>
           <% if current_user_is_admin %>
            <%= link_to 'Demote to regular user', demote_to_user_path(user.id), :class => "btn", :method => "post" %>
          <% end %>
        <% else %>
          <% if current_user_is_admin %>
            <%= link_to 'Promote to admin', promote_to_admin_path(user.id), :class => "btn", :method => "post" %>
          <% end %>
        <% end %>
        
         <%= link_to 'Show', user, :class => "btn btn-info" %>
        <% if current_user && (current_user_is_admin || user.id == current_user.id) %>
          <%= link_to 'Edit', edit_user_path(user), :class => "btn" %>
          <%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %>

        <% end %>
      </div>
    </td> 
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<div>

<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path, :class => "btn btn-inverse" %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
  <% if current_user_is_admin %>
    <% if @user.role != "admin" %>
        <%= link_to 'Promote user to admin', promote_to_admin_path(@user.id), :class => "btn", :method => "post" %>
    <% else %>
        <%= link_to 'Demote admin to regular user', demote_to_user_path(@user.id), :class => "btn", :method => "post" %>
    <% end %>
  <% end %>
</p>


<%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-primary" %> 
<%= link_to 'User listing', users_path, :class => "btn btn-info" %>