config/routes.rb
Ultimatejoke::Application.routes.draw do

  resources :users

    root to: 'static_pages#home'

    resources :jokes
    resource :user_session
    
    put '/jokes/:id/:action' => 'jokes#upvote'
	put '/jokes/:id/:action' => 'jokes#downvote'

    post '/users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_to_admin
    post '/users/:id/demote_to_user' => 'users#demote_to_user', :as => :demote_to_user

    post '/login' => 'user_sessions#create'
    get '/login' => 'user_sessions#new'
    get '/logout' => 'user_sessions#destroy'
 
end

app/models/joke.rb
class Joke < ActiveRecord::Base
	acts_as_votable
	attr_accessible :title, :content, :user_id, :image_url
	belongs_to :user
	validates_presence_of :title, :content
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController

	#before_filter :find_joke, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_filter :find_joke, only: [:show, :upvote, :downvote]
  	before_filter :require_user, except: [:index, :show]
	before_filter :find_user_joke, only: [:edit, :update, :destroy]
	before_filter :checkforuploadedfile, only: [:update, :create]
	#load_and_authorize_resource
	#skip_authorize_resource only: [:index, :show]

	def index
		@jokes = Joke.all
	end

	def new
		@joke = Joke.new
	end

	def checkforuploadedfile
		if params[:joke] && !params[:joke][:image_data].blank?
			@image_data = params[:joke][:image_data]
			params[:joke][:image_url] = @image_data.original_filename
			params[:joke].delete(:image_data)
		end
  	end

  	def saveuploadedfile
  		if @image_data != nil
  			file_data = @image_data
  			File.open(Rails.root.join('app', 'assets', 'images', file_data.original_filename), 'wb') do |file|
    			file.write(file_data.read)
    		end
    		@image_data = nil
  		end
  	end

	def create
		@joke = Joke.new(params[:joke])
		@joke.user = current_user

		if @joke.save
			saveuploadedfile
			flash[:success] = "Joke saved successfully!"
			redirect_to jokes_path
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @joke.update_attributes(params[:joke])
			saveuploadedfile
			flash[:success] = "Joke updated successfully!"
			redirect_to :joke
		else
			render :edit
		end
	end

	def destroy
		if @joke.destroy
			flash[:success] = "Joke deleted successfully!"
			redirect_to jokes_path
		end
	end

	def upvote
		@joke.liked_by current_user
   		redirect_to @joke
	end

	def downvote
	   	@joke.downvote_from current_user
  	  	redirect_to(@joke)
	end

	def find_joke
		@joke = Joke.find(params[:id])
	end

	def find_user_joke
		@joke = Joke.find(params[:id])
		if @joke.user_id != current_user.id && !current_user_is_admin
			flash[:error] = "Not authorized!"
			redirect_to jokes_path
		end
	end
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/jokes/_form.html.erb
<div>
	<%= form_for @joke do |f| %>
		<div>
		<%= f.label :title %>
		<%= f.text_field :title, :placeholder => "Insert the title of your joke..." %>
		</div>

		<div>
		<%= f.label :content %>
		<%= f.text_area :content, :class => "joke-content-textarea", :placeholder => "Write your joke here..." %>
		</div>

		<%= f.label :image_url %>
		<%= f.text_field :image_url, :class => "external-image-url-input", :placeholder => "Insert URL of a picture here..." %>

		<div class='image-preview-wrapper'>
			<p class="image-loadingerror-message"></p>
			<img class='preview-image'/>
		</div>
		<p> Or upload your own image </p>

		<%= f.file_field :image_data %>

		<div>
		<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/jokes/_sidebar.html.erb
<div class="span4">
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li class="nav-header">User info:</li>
			<% if current_user %>
				<li><%= link_to "My profile", user_path(current_user.id) %></li>
			<% else %>	
				<li><%= link_to "Sign up now to submit your own jokes!", new_user_path %></li>
			<% end %>		

			<li class="nav-header">Jokes:</li>
			<li><%= link_to "All jokes", jokes_path %></li>
			<% if current_user %>
				<li><%= link_to "New joke", new_joke_path %></li>
				<!-- <li>My Jokes (todo)</li> -->
			<% end %>	
		</ul>
	</div>
</div>

app/views/jokes/edit.html.erb
<%= render partial: 'sidebar' %>

<div class="span8">
	<h3>Edit joke: <%= @joke.title %></h3>
	<%= render partial: 'form' %>
</div>

app/views/jokes/index.html.erb
<%= render partial: 'sidebar' %>

<div class="span8">
	<h3>New jokes:</h3>
	<% @jokes.each do |j| %>
		<div class="row-fluid jokes-container">
			<h3 class='joke-title'><%= link_to j.title, joke_path(j) %></h3>
			<p class='joke-content'><%= j.content %></p>
			<% if j.image_url %>
				<img class='joke-image' src="<%= image_path(j.image_url) %>" />
			<% end %>
			<% if j.user && j.user.email %>
				<p class='joke-author'>By: <%= link_to j.user.email, user_path(j.user) %></p>
			<% else %>
				<p class='joke-author'>By: <span class='italic'>Removed user-account</span></p>
			<% end %>
		</div>
		<% if (current_user && j.user.id && current_user.id == j.user.id) || current_user_is_admin  %>
		<div class="btn-group">
			  <%= link_to "Edit", edit_joke_path(j), :class=>'btn btn-info' %>
			  <%= link_to "Delete", j, method: :delete, data: {confirm: 'Are you sure?'}, :class=>'btn btn-danger' %>
		</div>
		<% end %>
		
		<% if current_user %>
		<div class="btn-group">
		<%= link_to 'Upvote', 
			{:controller =>"jokes", :action => "upvote", :id => j.id}, :class => 'btn btn-success', method: :put %>
		<%= link_to 'Downvote', 
			{:controller =>"jokes", :action => "downvote", :id => j.id}, :class => 'btn btn-warning', method: :put %>
		</div>
		<% end %>
		<hr />
	<% end %>
</div>

app/views/jokes/new.html.erb
<%= render partial: 'sidebar' %>

<div class="span8">

	<h3>Create a new joke</h3>
	<%= render partial: 'form' %>
</div>

app/views/jokes/show.html.erb
<%= render partial: 'sidebar' %>

<div class="span8">
	<div class="row-fluid jokes-container">
		<h3><%= @joke.title %></h3>
		<p><%= @joke.content %></p>
		<% if @joke.image_url %>
			<img class='joke-image' src="<%= image_path(@joke.image_url) %>" />
		<% end %>
		<dl class="dl-horizontal">
			<dt>Upvotes:</dt>
			<dd><%= @joke.likes.size %></dd>
			<dt>Downvotes:</dt>
			<dd><%= @joke.dislikes.size %></dd>
		</dl>

		<% if current_user && @joke.user.id && current_user.id == @joke.user.id %>
		<div class="btn-group">
			  <%= link_to "Edit", edit_joke_path(@joke), :class=>'btn btn-info' %>
			  <%= link_to "Delete", @joke, method: :delete, data: {confirm: 'Are you sure?'}, :class=>'btn btn-danger' %>
		</div>
		<% end %>

		<% if current_user %>
		<div class="btn-group">
		<%= link_to 'Upvote', 
			{:controller =>"jokes", :action => "upvote", :id => @joke.id}, :class => 'btn btn-success', method: :put %>
		<%= link_to 'Downvote', 
			{:controller =>"jokes", :action => "downvote", :id => @joke.id}, :class => 'btn btn-warning', method: :put %>
		</div>
		<% end %>
	</div>
</div>