config/routes.rb
Ultimatejoke::Application.routes.draw do

  resources :users

    root to: 'static_pages#home'

    resources :jokes
    resource :user_session
    
    put '/jokes/:id/:action' => 'jokes#upvote'
	put '/jokes/:id/:action' => 'jokes#downvote'

    post '/users/:id/promote_to_admin' => 'users#promote_to_admin', :as => :promote_to_admin
    post '/users/:id/demote_to_user' => 'users#demote_to_user', :as => :demote_to_user

    post '/login' => 'user_sessions#create'
    get '/login' => 'user_sessions#new'
    get '/logout' => 'user_sessions#destroy'
 
end

app/views/layouts/_footer.html.erb
<footer class="footer container" style="padding-top:20px;">
	<div class="well well-small">
		Ultimate Jokes - Funniest Sh!t on the Planet<br /><br />
	<small>
		Created by: <br />
		Joonas Ahola <br />
		Markus Aro <br />
		Teemu Tiilikainen
	</small>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Ultimate Jokes", root_path, id: "logo", class: "brand" %>
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Home", root_path %>
					</li>
					<li>
						<%= link_to "Jokes", jokes_path %>
					</li>
					<li>
						<% if current_user %>
							<%= link_to current_user.email, user_path(current_user.id) %>
					</li>
					<li>
							<%= link_to "Logout", logout_path %>
					</li>
						<% else %>
							<%= link_to "Sign in!", login_path %>
						<% end %>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ultimate Jokes!</title>
		<%= stylesheet_link_tag "application", media: "all" %>
		<%= javascript_include_tag "application", media: "all" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
		<style>
			body {
				padding-top: 60px;
			}
		</style>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key%>">
				<%= value%>
			</div>
			<%end%>

			<div class="container">
				<div class="row-fluid">
					<%= yield %>
				</div>
			</div>

			<%= render 'layouts/footer' %>
			<!--<%= debug(params) if Rails.env.development? %> -->
		</div>
	</body>
</html>